version: "3.9"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver2019
    environment:
      - ACCEPT_EULA:Y
      - SA_PASSWORD:Password2022
    ports:
      - "1433:1433"
    volumes:
      - sqlserver2019:/var/opt/mssql
volumes:
    sqlserver2019:  